package project.ktc.springboot_app.upload.dto;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** DTO for video metadata response from Cloudinary */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VideoMetadataResponseDto {

	/** Title/name of the video (usually the public_id or original filename) */
	private String title;

	/** Video format (e.g., mp4, webm, mov, etc.) */
	private String format;

	/** Duration of the video in seconds */
	private Double duration;

	/** Thumbnail URL generated by Cloudinary */
	private String thumbnail;

	/** Video width in pixels */
	private Integer width;

	/** Video height in pixels */
	private Integer height;

	/** File size in bytes */
	private Long sizeBytes;

	/** Original video URL on Cloudinary */
	private String videoUrl;

	/** Public ID of the video on Cloudinary */
	private String publicId;

	/** Timestamp when metadata was retrieved */
	private LocalDateTime retrievedAt;
}
